manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: billksun
      url-base: https://github.com/billksun
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    # Corne dongle config repo
    - name: zmk-config
      remote: billksun
      revision: main
  self:
    path: config
